/*
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
*/

-- By using type: "operations" and "CREATE TABLE IF NOT EXISTS", 
-- Dataform will create it only if it's missing, but to NEVER drop or
-- recreate it on subsequent runs.
config {
  type: "operations",
  tags: ["init"]
}

--TODO: CREATE DATASET IF NOT EXISTS or this operation will fail the first time run

CREATE TABLE IF NOT EXISTS 
${ref(dataform.projectConfig.vars.log_table_name)}
(
  process_id INT64, -- no parallel processing support, batch only
  process_name STRING,
  process_start_time TIMESTAMP,
  process_end_time TIMESTAMP, -- only set to NON NULL if job completed successfully, this column is populated by the final step.
  process_msg STRING,
  source_table STRING, -- source table for raw gcp export partitioned by _PARTITIONTIME
  dest_table STRING, -- dest table for repartitioned and flattened gcp export
  records_added INT64,
  max_source_date DATE, -- used as the "bookmark" for incremental loads to the base table
  usage_dates_processed ARRAY<DATE>, -- used to track which usage_start_time partitioned to process for downstream aggregates
  max_dest_date DATE
);